server:
  servlet:
    context-path: /nginx

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nginx?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver